"""Added job categories

Revision ID: 779234063474
Revises: a68fa46355d0
Create Date: 2023-04-30 01:50:24.343998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '779234063474'
down_revision = 'a68fa46355d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association_jobs_to_categories',
    sa.Column('job', sa.Integer(), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['job'], ['jobs.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_jobs_to_categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
