"""1

Revision ID: 84076ce67a7c
Revises: 
Create Date: 2023-04-27 22:59:26.257578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84076ce67a7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('surname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'surname')
    # ### end Alembic commands ###
