"""Modernized relationship of users to departments

Revision ID: 9bf50b07bfd9
Revises: 45c79b2eb37c
Create Date: 2023-04-29 23:42:07.572581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bf50b07bfd9'
down_revision = '45c79b2eb37c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_users_to_deps',
    sa.Column('department', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], )
    )
    op.drop_column('departments', 'members')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('members', sa.VARCHAR(), nullable=True))
    op.drop_table('association_users_to_deps')
    # ### end Alembic commands ###
