"""Modernized relationship of users to jobs

Revision ID: a68fa46355d0
Revises: 9bf50b07bfd9
Create Date: 2023-04-30 00:08:13.281613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a68fa46355d0'
down_revision = '9bf50b07bfd9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'collaborators')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('collaborators', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
